binary_data_noChord_path: "data/binary/words" # the binary data path

# ----------------------------------------
# Pretrain | Skeleton data
# ----------------------------------------
raw_skeleton_data_dir_train: '/mnt/nextlab/xinda/MusicGeneration/Paper_SKeleton_Framework/Dataset/v20220517/wikifornia/13_dataset_held50/Wikifornia_rhythmSkeleton/train'
raw_skeleton_data_dir_test: '/mnt/nextlab/xinda/MusicGeneration/Paper_SKeleton_Framework/Dataset/v20220517/wikifornia/13_dataset_held50/Wikifornia_rhythmSkeleton/test'
config_path_small_noChord: paper_tasks/model/TransforXL_Small_noChord.yaml

# save dictionary
binary_data_dir: "data/binary" # the binary data path
batch_size: 10


# Model
hidden_size: 256
num_heads: 4
enc_layers: 4
dec_layers: 4
dropout: 0.2
dec_ffn_kernel_size: 1
enc_ffn_kernel_size: 1
ffn_act: relu
ffn_padding: SAME

# optimizer
lr: 0.001 # start from 2.0
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
weight_decay: 0

# early stopping
patience: 10




# max_sentences: 10 # batch size
# max_eval_sentences: 10 # number of test sentence


# # ------------------- global parameters settings ------------------- #
# MELODDY_RATIO: 0.6
# DEFAULT_TICKS_PER_BEAT: 480 # resolution (the number of ticks per quarter note), e.g., 480 ticks per quarter note.
# STEP_PER_BAR: 192 # we divide a bar into 64 timesteps
# instru2track: {'Drums':1, 'Piano':2, 'Percussion':3, 'Organ':4, 'Guitar':5, 'Bass':6, 'Strings':7, 'Brass':8, 'Lead':9}
# instru2program: ['Drums':0, 'Piano':0, 'Percussion':12, 'Organ':16, 'Guitar':31, 'Bass':33, 'Strings':48, 'Brass':61, 'Lead':80] # the mapping rules between instruments and program in midi
# STRUCTURE: {"Intro":1,"Verse":2, "Pre-chorus":3, "Chorus":4, "Re-intro":5, "Bridge":6,"Outro":7, "Others":8} # Structure





# # ------------------------------
# # pretrain | Melody data
# # ------------------------------
# raw_melody_data_dir_train: '/mnt/nfs-shared/xinda/MDP/data/process/sys_skeleton_melody/data_version/20211218/wikifonia_v5/melody/train'
# raw_melody_data_dir_valid: '/mnt/nfs-shared/xinda/MDP/data/process/sys_skeleton_melody/data_version/20211218/wikifonia_v5/melody/valid'
# raw_melody_data_dir_test: '/mnt/nfs-shared/xinda/MDP/data/process/sys_skeleton_melody/data_version/20211218/wikifonia_v5/melody/test'

# # pretrain | Skeleton data
# raw_skeleton_data_dir_train: '/mnt/nfs-shared/xinda/MDP/data/process/sys_skeleton_melody/data_version/20211218/wikifonia_v5/skeleton/train'
# raw_skeleton_data_dir_valid: '/mnt/nfs-shared/xinda/MDP/data/process/sys_skeleton_melody/data_version/20211218/wikifonia_v5/skeleton/valid'
# raw_skeleton_data_dir_test: '/mnt/nfs-shared/xinda/MDP/data/process/sys_skeleton_melody/data_version/20211218/wikifonia_v5/skeleton/test'

# checkpoint_dir: 'checkpoints/'
# melody_generation_output_dir: 'checkpoints/output'










# # ------------------- data path settings ------------------- #
# dataset_root: '/mnt/nfs-shared/xinda/MDP/data/process/sys_skeleton_melody/data_version/20211215'
# melody_root: 'wikifonia_midi_12_2_melody'
# skeleton_root: 'wikifonia_midi_12_2_skeleton'


# # ------------------- binary processing settings and Skeleton  Embedding settings------------------- #
# # 假设1：常规一首歌3-4分钟，即180s-240s
# # 假设2：常规BPM=120， 一个小节2s，
# # 假设3：常规一个乐句包含4个小节
# # 推理结论，常规一首歌在90-120小节，半首歌在45-60小节，包含乐句在11-15个。因此，我们假设以60个小节和15个乐句为一个计算循环单位来处理数据的（具体在Embedding中）
# tempo_class_szie: 3
# # structure_type_size: 8
# # MAX_PHRASE: 15
MAX_BARS: 64
# MAX_POSITION_UNIT: 96
# VELOCITY_BINS: 32
# MAX_DURATION: 102


# MAX_POSITION: 96
# MAX_PITCH: 128


# phrase_inner_bar_size: 10 # 考虑最极端的情况，小节数量与乐句数量一致；即 phrase_size = bar_voc_size
# # pos_voc_size: 32
# use_style: false
# use_velocity: true
# use_track_mask: true



# shuffle: True # 是否随机
# num_valid: 50 # 验证数据集的数量

# task_type: # tasks Type （任务类型）
# #  cond_info: ['Structure','Phrase','Chord']
#   cond_info: []
#   cond: [] # 增加和弦类型：cond: ['Structure','Phrase','Chord', 'Lead']
#   target: ['Lead']


# # ------------------- structure dataset processing settings ------------------- #
# num_test_samples: 20 # num_test_samples
# NUM_WORKERS: 10 # 8
# max_test_sentences: 1
sentence_maxlen: 512
# skeleton_sentence_maxlen: 400
# endless_ds: false # 不重复
# max_sentences_finetune: 10 # batch size
# max_eval_sentences_finetune: 1 # number of test sentence
# max_test_sentences_finetune: 1






# # ---------- Checkpoint Setting ---------#
num_ckpt_keep: 5


# # --------- Trainer Settings----------- #
total_epoch: 1000
clip_grad_norm: 1
log_interval: 100 # # How often to log within steps
val_check_interval: 10000 #  How often to check the validation set. use int to check every n steps (batches).

# # --------- pl.LightingModule Settings----------- #
# use_gpu: true



# # --------- Inference Settings----------- #
# checkpoint_path: '/mnt/nfs-shared/xinda/MusicGeneration/neural-music/checkpoints/all/melody/skeleton_based_melody_generation_pretrain/early_stopping_checkpoin_validLoss_173.671_140_0907.pt'
# test_midi_path: '/mnt/nfs-shared/xinda/MusicGeneration/neural-music/data/raw/zhpop_S/melody_process/melody_extraction_60percent'
# save_pre_dir: '/mnt/nfs-shared/xinda/MusicGeneration/neural-music/sevice/skeleton_generation/skeleton_inference'
# inference_test_midi: 20
# num_select_bars: 4
# inference_bar: 32
# inference_max_tokens: 800
# topk: 5 # default 5
# temperature: 1.2 # default 1.2




# # 用于限制每个文件夹最多读取多少个文件; 默认等于-1，表示使用读取的文件夹中所有的MIDI文件
# max_samples_per_ds: -1


# # Track filter conditions
# max_n_beats: 1000
# min_n_beats: 16
# min_n_notes: 50
# min_n_pitches: 10
# max_cross_bar_rate: 0.15






# # max sentence batch size| 每批选择16个MIDI片段





# max_tokens: 31250
# max_updates: 320000 # default =  320000, wxd : add 100000 420000 to updates for transfer learning

# accumulate_grad_batches: 1


# debug: false


# infer: false

# lambda_attr: 1.0
# load_ckpt: ''


# max_eval_tokens: -1

# check_val_every_n_epoch: 10


# num_sanity_val_steps: 5

# remove_empty_bar: false
# save_best: true
# save_ckpt: true
# save_codes:
#   - configs
#   - tasks/mumidi
#   - utils
# seed: 1234
# sort_by_len: true


# test_num: 100


# warmup_updates: 8000


# # infer
# instru2vellimits: {}
# n_target_bar: 32
# cond_bar_selection: 4

# # melody generation from sketch

# melody_generation_fromsketch_output_dir: '/mnt/nfs-shared/xinda/MusicGeneration/Yuyin/toolkit/REMI_Nor2_sel_improved_mid_Track3_addDrumsStrings'
# #model_configs: ['checkpoints/melody_generationcd']
# # melody generation from prompt
# input_dir: '/mnt/nfs-shared/xinda/MusicGeneration/Yuyin/toolkit/REMI_Nor2_sel_improved_mid_Track3'
# tmp_dir: '/mnt/nfs-shared/xinda/MusicGeneration/Yuyin/data/tmp_dir'
