# save dictionary
binary_data_dir: "data/binary"                  # the binary data path

# pretrain skeleton data
binary_data_noChord_path: "data/binary/words"   # the binary data path
raw_skeleton_data_dir_train: '/mnt/nextlab/xinda/MusicGeneration/Paper_SKeleton_Framework/Dataset/v20220517/wikifornia/13_dataset_held50/Wikifornia_rhythmSkeleton/train'
raw_skeleton_data_dir_test: '/mnt/nextlab/xinda/MusicGeneration/Paper_SKeleton_Framework/Dataset/v20220517/wikifornia/13_dataset_held50/Wikifornia_rhythmSkeleton/test'
config_path_small_noChord: paper_tasks/model/TransforXL_Small_noChord.yaml

# Model
hidden_size: 256
num_heads: 4
enc_layers: 4
dec_layers: 4
dropout: 0.2
dec_ffn_kernel_size: 1
enc_ffn_kernel_size: 1
ffn_act: relu
ffn_padding: SAME

# optimizer
batch_size: 10
lr: 0.001 
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
weight_decay: 0

# early stopping
patience: 10

MAX_BARS: 64
sentence_maxlen: 512


# trainer settings
total_epoch: 1000
clip_grad_norm: 1
num_ckpt_keep: 5
log_interval: 100 # # How often to log within steps
val_check_interval: 10000 #  How often to check the validation set. use int to check every n steps (batches).






